FROM node:20-alpine AS build

WORKDIR /app

RUN apk add --no-cache python3 build-base py3-pip

COPY package.json package-lock.json ./

RUN npm cache clean --force && rm -rf node_modules package-lock.json

RUN npm install -g @angular/cli

RUN npm install

COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0"]